# Generated by Django 4.0.5 on 2025-05-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_department_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('job_description', models.TextField(max_length=2000)),
                ('reported_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='employees.employee',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(
                fields=('employee', 'reported_on'), name='uq_daily_report_01'
            ),
        ),
    ]
