# Generated by Django 4.0.5 on 2025-05-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='daily_report_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
