# Generated by Django 4.0.5 on 2025-05-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department_employee_user'),
        ('daily_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportComment',
            fields=[
                (
                    'daily_report_code',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ('comment', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'daily_report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='daily_reports.dailyreport',
                    ),
                ),
                (
                    'employee_code',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='employees.employee',
                    ),
                ),
            ],
        ),
    ]
