# Generated by Django 4.0.5 on 2025-05-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0002_dailyreportcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='daily_report_code',
        ),
        migrations.RemoveField(
            model_name='dailyreportcomment',
            name='daily_report_code',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyreportcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
